# Common headers for both website and Storybook
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://www.youtube.com/"
    Access-Control-Allow-Origin = "*"

# Common redirects for both website and Storybook
[[redirects]]
  from = "/definitions"
  to = "https://github.com/asyncapi/spec-json-schemas/tree/master/schemas"
  status = 200

[[redirects]]
  from = "/schema-store"
  to = "https://github.com/asyncapi/spec-json-schemas/tree/master/schemas"
  status = 200

# Common environment variables for both builds
[build.environment]
  NPM_FLAGS = "--production=false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

# Plugins for both builds
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Default build settings
[build]
  command = "npm run build:${DEPLOY_TARGET}"  # Use the environment variable to determine the build command
  publish = "out"                              # Default publish directory

# Conditional publish directory based on DEPLOY_TARGET
[build]
  [[commands]]
    command = "npm run build:storybook"       # Command for Storybook
    publish = "storybook-static"               # Publish directory for Storybook
    if = "DEPLOY_TARGET == 'storybook'"       # Only run if DEPLOY_TARGET is 'storybook'