[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://www.youtube.com/"
    Access-Control-Allow-Origin = "*"

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NPM_FLAGS = "--production=false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"

# Used by JSON Schema definitions fetched directly from AsyncAPI website
[[redirects]]
  from = "/definitions"
  to = "https://github.com/asyncapi/spec-json-schemas/tree/master/schemas"
  status = 200

# Used by JSON Schema definitions fetched from schemastore.org
[[redirects]]
  from = "/schema-store"
  to = "https://github.com/asyncapi/spec-json-schemas/tree/master/schemas"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
